config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/TEAR-ERC/tandem:
      branch: main
      repo: https://github.com/TEAR-ERC/tandem
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/TEAR-ERC/tandem git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-apricot-zebra.sh
        container: qc.acc_muzzy-purple-argentino
  QC.Doc:
    repos:
      github.com/TEAR-ERC/tandem find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-rust-toad.sh
        container: qc.doc_tacky-sapphire-frigatebird
      github.com/TEAR-ERC/tandem git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-auburn-cuscus.sh
        container: qc.doc_snazzy-vermilion-retriever
      github.com/TEAR-ERC/tandem markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-burgundy-dogfish.sh
        container: qc.doc_zippy-cerulean-rottweiler
      github.com/TEAR-ERC/tandem restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-tan-crane.sh
        container: qc.doc_thirsty-viridian-chameleon
  QC.Lic:
    repos:
      github.com/TEAR-ERC/tandem licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-razzmatazz-wolfhound.sh
        container: qc.lic_snazzy-black-russel
  QC.Sec:
    repos:
      github.com/TEAR-ERC/tandem bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-emerald-ostrich.sh
        container: qc.sec_woozy-maroon-eel
  QC.Sty:
    repos:
      github.com/TEAR-ERC/tandem flake8:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-cyan-toad.sh
        container: qc.sty_wheezy-ochre-coral
  QC.Ver:
    repos:
      github.com/TEAR-ERC/tandem get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-bistre-catfish.sh
        container: qc.ver_hazy-coral-molly
timeout: 5400
