config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/TEAR-ERC/tandem:
      branch: main
      repo: https://github.com/TEAR-ERC/tandem
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/TEAR-ERC/tandem git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-dandelion-tang.sh
        container: qc.acc_grumpy-auburn-bobcat
  QC.Doc:
    repos:
      github.com/TEAR-ERC/tandem find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-violet-mongoose.sh
        container: qc.doc_chummy-khaki-mole
      github.com/TEAR-ERC/tandem git:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-beige-ray.sh
        container: qc.doc_skimpy-white-chipmunk
      github.com/TEAR-ERC/tandem markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-eggplant-bear.sh
        container: qc.doc_sloppy-violet-fossa
      github.com/TEAR-ERC/tandem restructuredtext-lint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-rust-civet.sh
        container: qc.doc_skanky-copper-quoll
  QC.Lic:
    repos:
      github.com/TEAR-ERC/tandem licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-asparagus-giraffe.sh
        container: qc.lic_beady-scarlet-turkey
  QC.Sec:
    repos:
      github.com/TEAR-ERC/tandem bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-smalt-badger.sh
        container: qc.sec_ugly-pink-peccary
  QC.Sty:
    repos:
      github.com/TEAR-ERC/tandem flake8:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-persimmon-gibbon.sh
        container: qc.sty_shaky-blue-ocelot
  QC.Ver:
    repos:
      github.com/TEAR-ERC/tandem get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-blue-collie.sh
        container: qc.ver_flaky-teal-civet
timeout: 5400
